apiVersion: v1
kind: Pod
metadata:
  name: demopod
  labels:
    name: demopod
spec:
  containers:
  - name: application
    image: sivakarthi/go-web-app
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000